- src/handlers/artist_handler.rs
- src/handlers/auth_handler.rs
- src/handlers/scrapers/open_library.rs
- src/handlers/series_handler.rs
- src/handlers/subscriptions_handler.rs
- src/handlers/title_group_handler.rs
- src/handlers/user_handler.rs
Let actix-web do the work of deserializing our query strings using the built-in extractors.  Simplify the handler code by using custom types for query.
> handlers: use first-class deserializable types for query strings

- src/repositories/artist_repository.rs
- src/repositories/auth_repository.rs
- src/repositories/edition_group_repository.rs
- src/repositories/invitation_repository.rs
- src/repositories/master_group_repository.rs
- src/repositories/notification_repository.rs
- src/repositories/series_repository.rs
- src/repositories/subscriptions_repository.rs
- src/repositories/title_group_comment_repository.rs
- src/repositories/title_group_repository.rs
- src/repositories/torrent_repository.rs
- src/repositories/torrent_request_repository.rs
- src/repositories/torrent_request_vote_repository.rs
- src/repositories/user_repository.rs
Simplify the repositories such that they no longer know anything about being used from the context of actix_web.  This should be a maintained architectural goal.
> repos: isolate from actix_web

- src/handlers/artist_handler.rs
- src/handlers/auth_handler.rs
- src/handlers/edition_group_handler.rs
- src/handlers/invitation_handler.rs
- src/handlers/master_group_handler.rs
- src/handlers/series_handler.rs
- src/handlers/subscriptions_handler.rs
- src/handlers/title_group_comment_handler.rs
- src/handlers/title_group_handler.rs
- src/handlers/torrent_handler.rs
- src/handlers/torrent_request_handler.rs
- src/handlers/torrent_request_vote_handler.rs
- src/handlers/user_handler.rs
- src/lib.rs
- src/main.rs
- src/repositories/artist_repository.rs
- src/repositories/auth_repository.rs
- src/repositories/edition_group_repository.rs
- src/repositories/invitation_repository.rs
- src/repositories/master_group_repository.rs
- src/repositories/notification_repository.rs
- src/repositories/series_repository.rs
- src/repositories/subscriptions_repository.rs
- src/repositories/title_group_comment_repository.rs
- src/repositories/title_group_repository.rs
- src/repositories/torrent_repository.rs
- src/repositories/torrent_request_repository.rs
- src/repositories/torrent_request_vote_repository.rs
- src/repositories/user_repository.rs
- tests/test_auth.rs
Currently, only PgPool is used as app-state runtime data, but this is
limited.  Prepare to allow for additional fields to be added by lifting
out a top-level `Arcadia` type (currently only holding the `PgPool`).
This is preparation for reifying additional state data to facilitate
testing (namely: open signup state).
Note: stacks on #10
> arcadia: create a container for top-level app state

- src/handlers/artist_handler.rs
- src/handlers/auth_handler.rs
- src/handlers/edition_group_handler.rs
- src/handlers/invitation_handler.rs
- src/handlers/master_group_handler.rs
- src/handlers/series_handler.rs
- src/handlers/subscriptions_handler.rs
- src/handlers/title_group_comment_handler.rs
- src/handlers/title_group_handler.rs
- src/handlers/torrent_handler.rs
- src/handlers/torrent_request_handler.rs
- src/handlers/torrent_request_vote_handler.rs
- src/handlers/user_handler.rs
- src/lib.rs
- src/main.rs
- src/repositories/artist_repository.rs
- src/repositories/auth_repository.rs
- src/repositories/edition_group_repository.rs
- src/repositories/invitation_repository.rs
- src/repositories/master_group_repository.rs
- src/repositories/notification_repository.rs
- src/repositories/series_repository.rs
- src/repositories/subscriptions_repository.rs
- src/repositories/title_group_comment_repository.rs
- src/repositories/title_group_repository.rs
- src/repositories/torrent_repository.rs
- src/repositories/torrent_request_repository.rs
- src/repositories/torrent_request_vote_repository.rs
- src/repositories/user_repository.rs
- tests/test_auth.rs
Pull open signups state once from the environment, and store it as part
of the application state.  This facilitates testing absent of env
tweaking (which is global).
Note: stacked on #11
> testing: rework open signup state

- src/handlers/user_handler.rs
- tests/test_auth.rs
Add a test to hit an authenticated endpoint after logging in.  Should get some (limited) coverage to catch future regressions.
> testing: add coverage for User authentication actix integration

- src/handlers/artist_handler.rs
- src/handlers/auth_handler.rs
- src/handlers/edition_group_handler.rs
- src/handlers/invitation_handler.rs
- src/handlers/master_group_handler.rs
- src/handlers/series_handler.rs
- src/handlers/subscriptions_handler.rs
- src/handlers/title_group_comment_handler.rs
- src/handlers/title_group_handler.rs
- src/handlers/torrent_handler.rs
- src/handlers/torrent_request_handler.rs
- src/handlers/torrent_request_vote_handler.rs
- src/handlers/user_handler.rs
- src/lib.rs
- src/repositories/auth_repository.rs
Step 2 in reworking errors, this changes fallible handlers to use the top-level Error type, and reworks the implementations to use '?' for short-circuiting.
It also implements `actix_web::ResponseError` to generate JSON error responses for the frontend. The implementation of `status_code()` can be adjusted to generate appropriate status codes based on error (to come).
> handlers: rework error management

- .env
- src/handlers/scrapers/mod.rs
- src/handlers/scrapers/tmdb.rs
- src/lib.rs
- src/routes.rs
A first pass has been done to map the TMDB API-returned data fields and the title group data, it's likely it will need to be revisited with frontend integration.
Note that this API now requires the registration at TMDB and retreiving a bearer token from their development page.
> externaldb: initial tmdb support

- migrations/20250312215600_initdb.sql
- migrations/fixtures/fixtures.sql
- src/models/user.rs
- src/repositories/auth_repository.rs
A `passkey` will be encoded in the users' snatched torrent file, and is used to uniquely identify them to the tracker.  Make use of a 128-bit passkey, should give plenty of entropy to avoid bruteforce guessing attacks.
Postgres does not have a native u128 type, so instead marshal the generated 128-bit type into two 64-bit components, each inserted as an upper and lower pair.
While we're here, default the `settings` column to an empty dict to facilitate easier user insertions.
> user: allocate passkey on user registration

- tests/fixtures/with_test_user.sql
- tests/test_auth.rs
Tests were broken with the addition of the passkey and additional Arcadia parameters (torrent dir and frontend url).  Fix everything up and get them running again (and passing!).
> tests: fix with recent updates

- CONTRIBUTING.md
In addition, add preference to initializing the database with `cargo sqlx database setup`, which will create all the tables and run all migrations.
> contributing.md: fixup some spelling errors and add testing section

- .github/workflows/publish_images.yaml
Changes:
* adds a new workflow that builds and publishes the container image
Details:
Images will be published to `ghcr.io/arcadia-solutions/arcadia`. If the build is triggered off a merge to main, it will be tagged with the merge commit SHA. If the build is triggered off of a Github release, it will have the version number, e.g. 1.2 for v1.2
Here is test example from my fork: https://github.com/bees/arcadia-index/actions/runs/14477483681
> Publish index docker image to ghcr

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/publish_images.yaml
Changes:
* splits the ci.yml file into two specific FE/BE workflows
* Use [paths](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to only run the workflows when the subdirectory changes
Goal is to avoid unnecessary work. I originally kept everything in one file and tried to parse the diff but it was brittle - this is a lot more straightforward approach.
> Make workflows run conditionally

- .github/workflows/backend.yml
- backend/migrations/20250312215600_initdb.sql
- backend/src/handlers/scrapers/tmdb.rs
- backend/src/handlers/torrent_handler.rs
- backend/src/main.rs
- backend/src/models/edition_group.rs
- backend/src/models/title_group.rs
- backend/src/models/torrent.rs
- backend/src/repositories/edition_group_repository.rs
- backend/src/repositories/title_group_repository.rs
- backend/src/repositories/torrent_repository.rs
- backend/src/repositories/torrent_request_repository.rs
- backend/src/tracker/announce.rs
Clippy is a rust tool that does some basic static analysis.  Run it, and ensure that the backend comes out error and warning free.
In the process, this identified that the `category_enum` had both `Single` and `SingleCategory` members, but on the backend, they were being aliased.  Just opt to drop the latter.
Also, ensure clippy will run in CI.
> backend: make clippy green

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
Not only it fixes #66 it also now does schema checking, testing (+ building ofc) and linting in parallel as separate jobs with faster speed.
Also with separate jobs it's possible to make workflows (for example the docker one) wait for the build to complete successfully to not waste time building a docker image that won't work.
> Optimize CI workflows

- backend/src/api_doc.rs
- backend/src/handlers/artist_handler.rs
- backend/src/handlers/series_handler.rs
- backend/src/handlers/title_group_handler.rs
- backend/src/handlers/torrent_handler.rs
- backend/src/models/artist.rs
- backend/src/models/edition_group.rs
- backend/src/models/series.rs
- backend/src/models/title_group.rs
- backend/src/models/title_group_comment.rs
- backend/src/models/torrent.rs
- backend/src/models/user.rs
- backend/src/repositories/series_repository.rs
- backend/src/repositories/title_group_repository.rs
- backend/src/repositories/torrent_repository.rs
The goal is to have all api response types defined, to then use a package that translates either rust structs or openapi references into typescript types.
Here, the created struct `SeriesAndTitleGroupHierarchyLite` is only used in the api docs, and not used to deserialize sql query results, as they are already in json format. That provides better performance, but doesn't check if the struct is updated, if someone updates the sql query.
should clear https://github.com/Arcadia-Solutions/arcadia/issues/20
> defining nested structs

- backend/src/repositories/torrent_repository.rs
Postgres only supports signed integer types, which is why we always get a signed type back.  And yet, we interpret the bits as unsigned (or at least should have been!).
So, sign-extension strikes again.  If the lower portion of the passkey had the highest-order bit set, when casted to u128, all of the upper bits are set to 1, meaning the upper bits are wiped.
Fix this just by ensuring the bits are unsigned before extension.
> tracker: fix passkey in downloaded torrent

- backend/src/handlers/announce_handler.rs
- backend/src/repositories/peer_repository.rs
- backend/src/tracker/announce.rs
- backend/tests/test_announce.rs
The announce response from the tracker needs to ensure that the "peers" field in the dict encodes the peers into a (byte)string.  Previously, the tracker was instead encoding the peers as a list of 6-byte strings, but that was incorrect, which caused torrent clients to ignore the peer list.
With this fix, we can actually connect peers together :-)
> tracker: fix peer list in announce

- backend/CONTRIBUTING.md
This updates the documentation to use `http://localhost:8080/swagger-ui/` instead of `http://localhost:8080/swagger-ui` to prevent `HTTP ERROR 404` when accessing Swagger locally or via docker.
Why the trailing slash matters:
The route is configured using this wildcard pattern:
```
SwaggerUi::new("/swagger-ui/{_:.*}")
```
Whilst this may appear to support `/swagger-ui` and `/swagger-ui/`, the trailing slash is required for the correct loading of the Swagger UI.
Without the `/`, browsers will fail to load the interface. 
```
INFO  actix_web::middleware::logger] "GET /swagger-ui HTTP/1.1" 404 0 "-" "Mozilla/5.0...
```
http://localhost:8080/swagger-ui ----> HTTP 404 Error
http://localhost:8080/swagger-ui/ ---> Fully functional Swagger UI
> Add trailing slash to example Swagger API url for consistency

- backend/scripts/init_db.sh
The script previously failed immediately if the database wasn't available. Added retry logic with 30 attempts and 2-second intervals between retries to handle temporary database unavailability during startup.
Exit with success only after successful connection, or failure after all attempts are exhausted.
> fix(init_db): add retry logic for database connection

- backend/.env.example
- backend/Dockerfile
- compose.yml
Updated the docker config to support docker [BuildKit](https://docs.docker.com/build/buildkit/) for quicker builds and deployments by using layer caching.
Includes a modification to the sample .env file to enable BuildKit, as it cannot be strictly enforced on a repository level.
> Enhance docker config for quicker build/deploy
